### ISSUE TITLE
Kolorowanie nagłówków kart przedmiotów w zależności od rzadkości

### ISSUE THREAD

**Issue by ktos** [pollubnet/equipment-manager#1]
Można by dodać, aby nagłówki kart przedmiotów kolorowane były w zależności od rzadkości przedmiotu, w jakiejś skali kolorystycznej.

**Comment by Duke-Axer** [comment]
.

**Comment by DivineSin92** [comment]
.

**Comment by Duke-Axer** [comment]
@N3rWu6 @Duke-Axer

**Comment by ktos** [comment]
Fixed by #12 and #20.
