### ISSUE TITLE
Krótsza historia (opis) przedmiotu i rozwijanie po kliknięciu

### ISSUE THREAD

**Issue by ktos** [pollubnet/equipment-manager#2]
Obecnie opisy przedmiotów są czasami bardzo długie, lepiej by było, jakby były krótsze, np. zakończone `(...)` i rozwijały się dopiero po kliknięciu, w postaci jakiegoś tooltipa lub dialogu.

**Comment by Barsol6** [comment]
@Barsol6
@michal102

**Comment by ktos** [comment]
Fixed by #18
