### ISSUE TITLE
Wyrównanie do prawej statystyk przedmiotu

### ISSUE THREAD

**Issue by ktos** [pollubnet/equipment-manager#3]
Tabelka przedstawiająca statystyki przedmiotu jest wyrównana do lewej w każdej kolumnie, lepiej by było do prawej w kolumnie z wartościami liczbowymi.

**Comment by Sl0w1k** [comment]
Sl0w1k

**Comment by DivineSin92** [comment]
.

**Comment by DivineSin92** [comment]
@DivineSin92

**Comment by ktos** [comment]
solved in #11
