### ISSUE TITLE
Oddzielny komponent do statystyk przedmiotu

### ISSUE THREAD

**Issue by ktos** [pollubnet/equipment-manager#4]
Obecnie tabela jest wyświetlana oddzielnie w każdej karcie (i dla statystyk zsumowanych), może lepiej by było wydzielić to do oddzielnego komponentu.

**Comment by DScraftPL** [comment]
.

**Comment by Makrowave** [comment]
.

**Comment by DScraftPL** [comment]
> 
zadanie 4 gang 🤜

**Comment by purifetchi** [comment]
closed by #10
